#!/bin/bash
# Hook for cross building on docker hub

# https://daehne.net/docker/dockerhub/github/2018/12/09/building-arm-images-on-docker-hub.html
curl -L https://github.com/multiarch/qemu-user-static/releases/download/v3.0.0/qemu-arm-static -o qemu-arm-static
chmod 755 qemu-arm-static 
