#!/bin/bash
# Hook for cross building on docker hub

# https://daehne.net/docker/dockerhub/github/2018/12/09/building-arm-images-on-docker-hub.html
docker run --rm --privileged multiarch/qemu-user-static:register --reset 